README.md
scripts/apply-coding-style.sh
scripts/check-coding-style.sh
scripts/clang-format-diff.py

Make scripts/ directory and add clang-format-diff.py, check-coding-style.sh, and apply-coding-style.sh.
clang-format-diff.py is the actual script that checks the coding style, while the other two are shortcut for clang-format-diff.py.
You need clang-format to be installed to run it.

script: Add scripts for checking and applying coding style

---

RuntimeLibrary/plsan_handler.cpp
scripts/test-plsan.sh

Linking objects need to be done using clang++ because runtime library is written in C++. Therefore separate build and link process in the script.

script: Fix build and link errors when running test-plsan.sh

---

compiler-rt/lib/plsan/plsan.cpp
compiler-rt/lib/plsan/plsan.h
compiler-rt/lib/plsan/plsan_handler.cpp
compiler-rt/lib/plsan/plsan_handler.h
compiler-rt/lib/plsan/plsan_shadow.cpp

We cannot use sanitizer code with STL, so we remove STL and replace with sanitizer common library.
And this branch is not completed, but these commits are critical for other implementation, so open pr now.

Change STL to sanitizer common library

---

compiler-rt/lib/plsan/plsan.cpp
compiler-rt/lib/plsan/plsan.h
compiler-rt/lib/plsan/plsan_allocator.cpp
compiler-rt/lib/plsan/plsan_thread.cpp
llvm/include/llvm/Transforms/Instrumentation/PreciseLeakSanitizer.h
llvm/lib/Transforms/Instrumentation/PreciseLeakSanitizer.cpp

Simplify initialization of local variables and decreasing reference counts of local variables. Regardless of the type (even for non-pointer types), just initialize/finialize (check memory leak) using only the address and the size of an object. It simplifies the code pretty much and unnecessary instrumentation for variables that does not contain pointers can be optimized later.
Also, bug fixes are included for the PLSan allocator and runtime library.
9 false negative cases are fixed by this PR:
- testcases/c++/leak/class-1.cpp
- testcases/c++/leak/class-2.cpp
- testcases/c/leak/ftype-4.c
- testcases/c/leak/var_arr-5.c
- testcases/c/leak/var_arr-6.c
- testcases/c/leak/var_arr-2.c
- testcases/c/leak/var_arr-4.c
- testcases/c/leak/ftype-3.c
- testcases/c/leak/var_arr-3.c

Simplify handling local variables

---

scripts/test-plsan.sh

Since commit d24870bb1bb ("compiler-rt: Add precise leak report in lsan"), when the process is dead, PreciseLeakSanitizer report is printed.
If there's "DEADLYSIGNAL" in the output, consider this as crash instead. The current script consider this as leak because of the "PreciseLeakSanitizer" signature string in the output.

testcases: consider DEADLYSIGNAL as crash

---

compiler-rt/lib/plsan/plsan.cpp
compiler-rt/lib/plsan/plsan.h

Reverts hygoni/precise-leak-sanitizer#58
Because of this merge, the PreciseLeakSanitizer doesn't report leak location,
(but still the passes the test-plsan.sh script)

Revert "55 debugging from the hell"

---

compiler-rt/lib/plsan/plsan_allocator.cpp

It should fix SPEC CPU mcf_r crashes (although mine has not finished yet)

DO NOT MESS UP WITH METADATA WHEN ALLOCATED FROM THE SECONDARY ALLOCATOR

---

testcases/c/functional/builtin_alloca/builtin_alloca.c

As same as the crash in 502.gcc_r SPEC CPU2017 case, if a builtin alloca is not executed - a matching __plsan_free_local_variable() crashes. This is a testcase for this.

testcases: add __builtin_alloca() in non-entry basic blockc case

---

compiler-rt/lib/plsan/plsan.cpp
compiler-rt/lib/plsan/plsan_allocator.cpp
compiler-rt/lib/plsan/plsan_allocator.h
llvm/lib/Transforms/Instrumentation/PreciseLeakSanitizer.cpp

Some minor optimizations.
The biggest optimization is commit 30a6aaf66c5bd3c35d63fe37a37131cbd3e7c05b,
but others also adds up :)
Performance data:
======= before =======
test-arraylist : 696.91
test-avl-tree : 659.00
test-binary-heap : 251.29
test-binomial-heap : 190.36
test-bloom-filter : 4.20
test-compare-functions : 3.74
test-hash-functions : 20.80
test-hash-table : 120.31
test-list : 8.88
test-queue : 128.11
test-rb-tree : 186.42
test-set : 122.90
test-slist : 10.59
test-sortedarray : 10.89
test-trie : 18.90
=======after =======
test-arraylist : 146.57
test-avl-tree : 312.88
test-binary-heap : 118.90
test-binomial-heap : 85.22
test-bloom-filter : 6.44
test-compare-functions : 5.39
test-hash-functions : 15.69
test-hash-table : 55.86
test-list : 7.01
test-queue : 79.85
test-rb-tree : …

66 minor optimizations

---

compiler-rt/lib/plsan/plsan.cpp
compiler-rt/lib/plsan/plsan.h
llvm/include/llvm/Transforms/Instrumentation/PreciseLeakSanitizer.h
llvm/lib/Transforms/Instrumentation/PreciseLeakSanitizer.cpp

We implement memset_wrapper to avoid memset function intercepting last time. But now we don't intercept memset, so memset_wrapper just make overhead.
test-arraylist: 670.30 -> 665.20
test-avl-tree: 682.06 -> 665.32
test-binary-heap: 231.04 -> 209.20
test-binomial-heap: 183.66 -> 176.72
test-bloom-filter: 4.41 -> 4.29
test-compare-functions: 3.76 -> 4.17
test-hash-functions: 14.54 -> 15.65
test-hash-table: 120.21 -> 117.80
test-list: 6.84 -> 5.22
test-queue: 111.42 -> 100.20
test-rb-tree: 105.41 -> 131.28
test-set: 118.76 -> 108.76
test-slist: 5.89 -> 5.31
test-sortedarray: 7.27 -> 6.98
test-trie: 19.17 -> 18.56

Optimization: memset_wrapper to builtin memset

---

llvm/lib/Transforms/Instrumentation/PreciseLeakSanitizer.cpp

#84 
There is something wrong while handle builtin alloca.
It should be passed i1 type to argument but, now passes ptr type.

Hotfix: fix wrong argument instrumenting while handle builtin alloca

---

compiler-rt/lib/plsan/plsan.cpp
compiler-rt/lib/plsan/plsan.h
compiler-rt/lib/plsan/plsan_allocator.cpp
compiler-rt/lib/plsan/plsan_allocator.h

Plsan instrumented runtime functions are read same metadata in one function.
Reading metadata has big overhead, so it is reasonable to reduce this action.
Instead of use pointer argument, we solve this problem with using metadata argument.

Optimization: Do not read same metadata several times in same action

---

compiler-rt/lib/plsan/plsan_allocator.cpp

#88 
In PointsIntoChunk function in plsan_allocator, it got metadata with just pointer not chunk(from GetBlockBegin).
It makes bad pointer error in sanitizer allocator.

Fix unaligned pointer for secondary allocator

---

compiler-rt/lib/plsan/plsan_interceptors.cpp
scripts/test-plsan.sh
testcases/c/functional/threads/thread.c

This PR should fix thread-related issues for PLSan.
I checked that Vim does not crash, which crashed before because of PLSan's thread issues.

87 fix check failure when using threads

---

compiler-rt/lib/plsan/plsan.cpp
compiler-rt/lib/plsan/plsan.h

While initial implementation of the runtime library adopted singleton design pattern, it has no clear reason or benefit.
only PLSan adopting this pattern (unlike LSan / ASan) without any benefit doesn't help getting PLSan merged into mainline LLVM.
Let's get back to functions and variables like other sanitizers :) (visitor pattern is still useful for readability, but not singleton)

compiler-rt: Do not use singleton pattern for PLSan class

---

.github/workflows/CI.yml
compiler-rt/CMakeLists.txt
scripts/build-ci.sh

- Make CI builds 10x faster by caching using ccache
- Run [simple algorithm tests](https://github.com/fragglet/c-algorithms) and measure how much program becomes slower after instrumentation
- Generate flamegraphs while measuring performance, which can be downloaded in the "Artifacts" section

Github CI - much faster builds, automatic performance measurements

---

compiler-rt/lib/plsan/CMakeLists.txt

#95 
One of Clang optimization is omitting frame pointer. That's why PLSan cannot print last reference stack trace.
We can fix it with adding -fno-omit-frame-pointer flag when compile PLSan compiler-rt code.

Fix: Add -fno-omit-frame-pointer flag when build PLSan runtime library

---

compiler-rt/lib/lsan/lsan_common.cpp

The current implementation pushes new entry even if there is already existing the same entry. If there's already a leak with same alloc and lost stack trace, do not add new entry.

compiler-rt: Do not record same leak multiple times

---

compiler-rt/lib/plsan/plsan.cpp
compiler-rt/lib/plsan/plsan.h
compiler-rt/lib/plsan/plsan_interceptors.cpp
llvm/include/llvm/Transforms/Instrumentation/PreciseLeakSanitizer.h
llvm/lib/Transforms/Instrumentation/PreciseLeakSanitizer.cpp
scripts/test-plsan.sh

#96 
__plsan_free_local_variable calls InternalAlloc function per pointer variable in function.
InternalAlloc is dynamic allocation and too many InternalAlloc called when function return. It affects to PLSan slow down.
This pr resolve this problem with allocating one vector per thread to store all address that need to be stored in __plsan_free_local_variable. This method reduce InternalAlloc to just one time per thread.
And, there are memory leak that lazy_check didn't free all InternalAlloc memory block when llvm.stacksave and llvm.stackrestore are in another basic block. The method described above can fix this problem also.

96 optimization   plsan free local variable calls internalalloc that makes plsan slow down

---

compiler-rt/lib/plsan/plsan_allocator.cpp

the Deallocate() function set the object state to unallocated, but it did not free to the primary allocator.
let's free it.
On my machine with 64GiB ram, it was able to run a full SPEC CPU2017 benchmark (intrate)
(except for the Fortran one).

compiler-rt: Deallocate memory in Deallocate() function

---

compiler-rt/lib/plsan/plsan.cpp
compiler-rt/lib/plsan/plsan.h
compiler-rt/lib/plsan/plsan_allocator.cpp

Currently __plsan_free_local_variable() checks memory leaks for already-freed objects, and this always produces false positives. Just skip when encountered a freed object.

(Bugfix) commpiler-rt: Do not check memory leak for freed objects

---

compiler-rt/lib/plsan/plsan_allocator.cpp

Now that we use multi-level shadow scheme, IsSameObject() doesn't need to call GetBlockBegin() which is dozens of times slower. Just check if the two metadata from the pointers are the same.
This improves the slowdowns in SPEC CPU2017 502.gcc_r from 350x to 7x.

compiler-rt: Optimize IsSameObject()
